version: 2

sources:
  - name: airbnb
    database: airbnb  
    schema: raw  
    tables:
      - name: HOSTS
        identifier: RAW_HOSTS
      - name: LISTINGS
        identifier: RAW_LISTINGS
      - name: REVIEWS
        identifier: RAW_REVIEWS

 